/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misclases;

import java.awt.Color;

/**
 *
 * @author David Emilio
 */
public class Habitaciones extends javax.swing.JFrame {

    /**
     * Creates new form Habitaciones
     */
    String band;
    public Habitaciones(String band) {
        this.band = band;
        initComponents();
        this.getContentPane().setBackground(Color.black);
        
        if(band=="1") {
            jRadioButton101.setEnabled(false);
            jRadioButton102.setEnabled(false);
            jRadioButton103.setEnabled(false);
            jRadioButton104.setEnabled(false);
            jRadioButton105.setEnabled(false);
            jRadioButton106.setEnabled(false);
            jRadioButton107.setEnabled(false);
            jRadioButton108.setEnabled(false);
            jRadioButton109.setEnabled(false);
            jRadioButton110.setEnabled(false);
            jRadioButton111.setEnabled(false);
            jRadioButton112.setEnabled(false);
            jRadioButton208.setEnabled(false);
            jRadioButton209.setEnabled(false);
            jRadioButton210.setEnabled(false);
            jRadioButton211.setEnabled(false);
            jRadioButton212.setEnabled(false);
            jRadioButton213.setEnabled(false);
            jRadioButton214.setEnabled(false);
            jRadioButton215.setEnabled(false);
        }
        
        else if(band=="2") {
            jRadioButton101.setEnabled(false);
            jRadioButton102.setEnabled(false);
            jRadioButton103.setEnabled(false);
            jRadioButton104.setEnabled(false);
            jRadioButton105.setEnabled(false);
            jRadioButton106.setEnabled(false);
            jRadioButton107.setEnabled(false);
            jRadioButton113.setEnabled(false);
            jRadioButton114.setEnabled(false);
            jRadioButton115.setEnabled(false);
            jRadioButton201.setEnabled(false);
            jRadioButton202.setEnabled(false);
            jRadioButton203.setEnabled(false);
            jRadioButton204.setEnabled(false);
            jRadioButton205.setEnabled(false);
            jRadioButton206.setEnabled(false);
            jRadioButton207.setEnabled(false);
            jRadioButton213.setEnabled(false);
            jRadioButton214.setEnabled(false);
            jRadioButton215.setEnabled(false);
        }
        
        else if(band=="3") {
            jRadioButton108.setEnabled(false);
            jRadioButton109.setEnabled(false);
            jRadioButton110.setEnabled(false);
            jRadioButton111.setEnabled(false);
            jRadioButton112.setEnabled(false);
            jRadioButton113.setEnabled(false);
            jRadioButton114.setEnabled(false);
            jRadioButton115.setEnabled(false);
            jRadioButton201.setEnabled(false);
            jRadioButton202.setEnabled(false);
            jRadioButton203.setEnabled(false);
            jRadioButton204.setEnabled(false);
            jRadioButton205.setEnabled(false);
            jRadioButton206.setEnabled(false);
            jRadioButton207.setEnabled(false);
            jRadioButton208.setEnabled(false);
            jRadioButton209.setEnabled(false);
            jRadioButton210.setEnabled(false);
            jRadioButton211.setEnabled(false);
            jRadioButton212.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPisos = new javax.swing.ButtonGroup();
        jRadioButton101 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton102 = new javax.swing.JRadioButton();
        jRadioButton103 = new javax.swing.JRadioButton();
        jRadioButton104 = new javax.swing.JRadioButton();
        jRadioButton105 = new javax.swing.JRadioButton();
        jRadioButton106 = new javax.swing.JRadioButton();
        jRadioButton107 = new javax.swing.JRadioButton();
        jRadioButton108 = new javax.swing.JRadioButton();
        jRadioButton109 = new javax.swing.JRadioButton();
        jRadioButton110 = new javax.swing.JRadioButton();
        jRadioButton111 = new javax.swing.JRadioButton();
        jRadioButton112 = new javax.swing.JRadioButton();
        jRadioButton113 = new javax.swing.JRadioButton();
        jRadioButton114 = new javax.swing.JRadioButton();
        jRadioButton115 = new javax.swing.JRadioButton();
        jRadioButton201 = new javax.swing.JRadioButton();
        jRadioButton202 = new javax.swing.JRadioButton();
        jRadioButton203 = new javax.swing.JRadioButton();
        jRadioButton204 = new javax.swing.JRadioButton();
        jRadioButton205 = new javax.swing.JRadioButton();
        jRadioButton206 = new javax.swing.JRadioButton();
        jRadioButton207 = new javax.swing.JRadioButton();
        jRadioButton208 = new javax.swing.JRadioButton();
        jRadioButton209 = new javax.swing.JRadioButton();
        jRadioButton210 = new javax.swing.JRadioButton();
        jRadioButton211 = new javax.swing.JRadioButton();
        jRadioButton212 = new javax.swing.JRadioButton();
        jRadioButton213 = new javax.swing.JRadioButton();
        jRadioButton214 = new javax.swing.JRadioButton();
        jRadioButton215 = new javax.swing.JRadioButton();
        jButtonSeleccionarHabitacion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Habitaciones");
        setBackground(new java.awt.Color(0, 0, 0));

        buttonGroupPisos.add(jRadioButton101);
        jRadioButton101.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton101.setText("101");

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(184, 148, 79));
        jLabel1.setText("Habitaciones");

        buttonGroupPisos.add(jRadioButton102);
        jRadioButton102.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton102.setText("102");

        buttonGroupPisos.add(jRadioButton103);
        jRadioButton103.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton103.setText("103");

        buttonGroupPisos.add(jRadioButton104);
        jRadioButton104.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton104.setText("104");

        buttonGroupPisos.add(jRadioButton105);
        jRadioButton105.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton105.setText("105");

        buttonGroupPisos.add(jRadioButton106);
        jRadioButton106.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton106.setText("106");

        buttonGroupPisos.add(jRadioButton107);
        jRadioButton107.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton107.setText("107");

        buttonGroupPisos.add(jRadioButton108);
        jRadioButton108.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton108.setText("108");

        buttonGroupPisos.add(jRadioButton109);
        jRadioButton109.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton109.setText("109");

        buttonGroupPisos.add(jRadioButton110);
        jRadioButton110.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton110.setText("110");

        buttonGroupPisos.add(jRadioButton111);
        jRadioButton111.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton111.setText("111");

        buttonGroupPisos.add(jRadioButton112);
        jRadioButton112.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton112.setText("112");

        buttonGroupPisos.add(jRadioButton113);
        jRadioButton113.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton113.setText("113");

        buttonGroupPisos.add(jRadioButton114);
        jRadioButton114.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton114.setText("114");

        buttonGroupPisos.add(jRadioButton115);
        jRadioButton115.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton115.setText("115");

        buttonGroupPisos.add(jRadioButton201);
        jRadioButton201.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton201.setText("201");

        buttonGroupPisos.add(jRadioButton202);
        jRadioButton202.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton202.setText("202");

        buttonGroupPisos.add(jRadioButton203);
        jRadioButton203.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton203.setText("203");

        buttonGroupPisos.add(jRadioButton204);
        jRadioButton204.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton204.setText("204");

        buttonGroupPisos.add(jRadioButton205);
        jRadioButton205.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton205.setText("205");

        buttonGroupPisos.add(jRadioButton206);
        jRadioButton206.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton206.setText("206");

        buttonGroupPisos.add(jRadioButton207);
        jRadioButton207.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton207.setText("207");

        buttonGroupPisos.add(jRadioButton208);
        jRadioButton208.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton208.setText("208");

        buttonGroupPisos.add(jRadioButton209);
        jRadioButton209.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton209.setText("209");

        buttonGroupPisos.add(jRadioButton210);
        jRadioButton210.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton210.setText("210");

        buttonGroupPisos.add(jRadioButton211);
        jRadioButton211.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton211.setText("211");

        buttonGroupPisos.add(jRadioButton212);
        jRadioButton212.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton212.setText("212");

        buttonGroupPisos.add(jRadioButton213);
        jRadioButton213.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton213.setText("213");

        buttonGroupPisos.add(jRadioButton214);
        jRadioButton214.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton214.setText("214");

        buttonGroupPisos.add(jRadioButton215);
        jRadioButton215.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton215.setText("215");

        jButtonSeleccionarHabitacion.setText("Confirmar habitación");
        jButtonSeleccionarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarHabitacionActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/triple.png"))); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/doble.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sencilla.png"))); // NOI18N

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sencilla.png"))); // NOI18N

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/doble.png"))); // NOI18N

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/triple.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(184, 148, 79));
        jLabel8.setText("PISO 1");

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(184, 148, 79));
        jLabel9.setText("PISO 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton106)
                            .addComponent(jRadioButton107)
                            .addComponent(jRadioButton101)
                            .addComponent(jRadioButton102)
                            .addComponent(jRadioButton103)
                            .addComponent(jRadioButton104)
                            .addComponent(jRadioButton105))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSeleccionarHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton112)
                                    .addComponent(jRadioButton111)
                                    .addComponent(jRadioButton110)
                                    .addComponent(jRadioButton109)
                                    .addComponent(jRadioButton108))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton113)
                                    .addComponent(jRadioButton114)
                                    .addComponent(jRadioButton115)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton207)
                            .addComponent(jRadioButton206)
                            .addComponent(jRadioButton205)
                            .addComponent(jRadioButton204)
                            .addComponent(jRadioButton203)
                            .addComponent(jRadioButton202)
                            .addComponent(jRadioButton201))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton209)
                            .addComponent(jRadioButton210)
                            .addComponent(jRadioButton211)
                            .addComponent(jRadioButton212)
                            .addComponent(jRadioButton208))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton213)
                            .addComponent(jRadioButton214)
                            .addComponent(jRadioButton215)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jRadioButton101)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRadioButton108)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButton109)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButton110)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButton111)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButton112))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRadioButton102)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButton103)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButton104)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButton105)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButton106)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButton107)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jRadioButton113)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton114)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jRadioButton208)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton209)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton210)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton211)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton212)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jRadioButton213)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton214)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton215)
                                .addGap(57, 57, 57))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton201)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton202)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton203)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton204)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton205)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton206)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton207))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addComponent(jButtonSeleccionarHabitacion)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSeleccionarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarHabitacionActionPerformed
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_jButtonSeleccionarHabitacionActionPerformed
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Habitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Habitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Habitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Habitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Habitaciones().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupPisos;
    private javax.swing.JButton jButtonSeleccionarHabitacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton101;
    private javax.swing.JRadioButton jRadioButton102;
    private javax.swing.JRadioButton jRadioButton103;
    private javax.swing.JRadioButton jRadioButton104;
    private javax.swing.JRadioButton jRadioButton105;
    private javax.swing.JRadioButton jRadioButton106;
    private javax.swing.JRadioButton jRadioButton107;
    private javax.swing.JRadioButton jRadioButton108;
    private javax.swing.JRadioButton jRadioButton109;
    private javax.swing.JRadioButton jRadioButton110;
    private javax.swing.JRadioButton jRadioButton111;
    private javax.swing.JRadioButton jRadioButton112;
    private javax.swing.JRadioButton jRadioButton113;
    private javax.swing.JRadioButton jRadioButton114;
    private javax.swing.JRadioButton jRadioButton115;
    private javax.swing.JRadioButton jRadioButton201;
    private javax.swing.JRadioButton jRadioButton202;
    private javax.swing.JRadioButton jRadioButton203;
    private javax.swing.JRadioButton jRadioButton204;
    private javax.swing.JRadioButton jRadioButton205;
    private javax.swing.JRadioButton jRadioButton206;
    private javax.swing.JRadioButton jRadioButton207;
    private javax.swing.JRadioButton jRadioButton208;
    private javax.swing.JRadioButton jRadioButton209;
    private javax.swing.JRadioButton jRadioButton210;
    private javax.swing.JRadioButton jRadioButton211;
    private javax.swing.JRadioButton jRadioButton212;
    private javax.swing.JRadioButton jRadioButton213;
    private javax.swing.JRadioButton jRadioButton214;
    private javax.swing.JRadioButton jRadioButton215;
    // End of variables declaration//GEN-END:variables
}
