/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misclases;

/**
 *
 * @author David Emilio
 */
public class Habitaciones extends javax.swing.JFrame {

    /**
     * Creates new form Habitaciones
     */
    public Habitaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPiso1 = new javax.swing.ButtonGroup();
        buttonGroupPiso2 = new javax.swing.ButtonGroup();
        jRadioButton101 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton102 = new javax.swing.JRadioButton();
        jRadioButton103 = new javax.swing.JRadioButton();
        jRadioButton104 = new javax.swing.JRadioButton();
        jRadioButton105 = new javax.swing.JRadioButton();
        jRadioButton106 = new javax.swing.JRadioButton();
        jRadioButton107 = new javax.swing.JRadioButton();
        jRadioButton108 = new javax.swing.JRadioButton();
        jRadioButton109 = new javax.swing.JRadioButton();
        jRadioButton110 = new javax.swing.JRadioButton();
        jRadioButton111 = new javax.swing.JRadioButton();
        jRadioButton112 = new javax.swing.JRadioButton();
        jRadioButton113 = new javax.swing.JRadioButton();
        jRadioButton114 = new javax.swing.JRadioButton();
        jRadioButton115 = new javax.swing.JRadioButton();
        jRadioButton201 = new javax.swing.JRadioButton();
        jRadioButton202 = new javax.swing.JRadioButton();
        jRadioButton203 = new javax.swing.JRadioButton();
        jRadioButton204 = new javax.swing.JRadioButton();
        jRadioButton205 = new javax.swing.JRadioButton();
        jRadioButton206 = new javax.swing.JRadioButton();
        jRadioButton207 = new javax.swing.JRadioButton();
        jRadioButton208 = new javax.swing.JRadioButton();
        jRadioButton209 = new javax.swing.JRadioButton();
        jRadioButton210 = new javax.swing.JRadioButton();
        jRadioButton211 = new javax.swing.JRadioButton();
        jRadioButton212 = new javax.swing.JRadioButton();
        jRadioButton213 = new javax.swing.JRadioButton();
        jRadioButton214 = new javax.swing.JRadioButton();
        jRadioButton215 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroupPiso1.add(jRadioButton101);
        jRadioButton101.setText("101");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Habitaciones");

        buttonGroupPiso1.add(jRadioButton102);
        jRadioButton102.setText("102");

        buttonGroupPiso1.add(jRadioButton103);
        jRadioButton103.setText("103");

        buttonGroupPiso1.add(jRadioButton104);
        jRadioButton104.setText("104");

        buttonGroupPiso1.add(jRadioButton105);
        jRadioButton105.setText("105");

        buttonGroupPiso1.add(jRadioButton106);
        jRadioButton106.setText("106");

        buttonGroupPiso1.add(jRadioButton107);
        jRadioButton107.setText("107");

        buttonGroupPiso1.add(jRadioButton108);
        jRadioButton108.setText("108");

        buttonGroupPiso1.add(jRadioButton109);
        jRadioButton109.setText("109");

        buttonGroupPiso1.add(jRadioButton110);
        jRadioButton110.setText("110");

        buttonGroupPiso1.add(jRadioButton111);
        jRadioButton111.setText("111");

        buttonGroupPiso1.add(jRadioButton112);
        jRadioButton112.setText("112");

        buttonGroupPiso1.add(jRadioButton113);
        jRadioButton113.setText("113");

        buttonGroupPiso1.add(jRadioButton114);
        jRadioButton114.setText("114");

        buttonGroupPiso1.add(jRadioButton115);
        jRadioButton115.setText("115");

        buttonGroupPiso2.add(jRadioButton201);
        jRadioButton201.setText("201");

        buttonGroupPiso2.add(jRadioButton202);
        jRadioButton202.setText("202");

        buttonGroupPiso2.add(jRadioButton203);
        jRadioButton203.setText("203");

        buttonGroupPiso2.add(jRadioButton204);
        jRadioButton204.setText("204");

        buttonGroupPiso2.add(jRadioButton205);
        jRadioButton205.setText("205");

        buttonGroupPiso2.add(jRadioButton206);
        jRadioButton206.setText("206");

        buttonGroupPiso2.add(jRadioButton207);
        jRadioButton207.setText("207");

        buttonGroupPiso2.add(jRadioButton208);
        jRadioButton208.setText("208");

        buttonGroupPiso2.add(jRadioButton209);
        jRadioButton209.setText("209");

        buttonGroupPiso2.add(jRadioButton210);
        jRadioButton210.setText("210");

        buttonGroupPiso2.add(jRadioButton211);
        jRadioButton211.setText("211");

        buttonGroupPiso2.add(jRadioButton212);
        jRadioButton212.setText("212");

        buttonGroupPiso2.add(jRadioButton213);
        jRadioButton213.setText("213");

        buttonGroupPiso2.add(jRadioButton214);
        jRadioButton214.setText("214");

        buttonGroupPiso2.add(jRadioButton215);
        jRadioButton215.setText("215");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton106)
                            .addComponent(jRadioButton107)
                            .addComponent(jRadioButton101)
                            .addComponent(jRadioButton102)
                            .addComponent(jRadioButton103)
                            .addComponent(jRadioButton104)
                            .addComponent(jRadioButton105))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton112)
                                    .addComponent(jRadioButton111))
                                .addGap(296, 296, 296))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton110)
                                    .addComponent(jRadioButton109)
                                    .addComponent(jRadioButton108))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton113)
                                    .addComponent(jRadioButton114)
                                    .addComponent(jRadioButton115))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton207)
                            .addComponent(jRadioButton206)
                            .addComponent(jRadioButton205)
                            .addComponent(jRadioButton204)
                            .addComponent(jRadioButton203)
                            .addComponent(jRadioButton202)
                            .addComponent(jRadioButton201))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(296, 296, 296)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton213)
                                    .addComponent(jRadioButton214)
                                    .addComponent(jRadioButton215))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton208)
                                    .addComponent(jRadioButton209)
                                    .addComponent(jRadioButton210)
                                    .addComponent(jRadioButton211)
                                    .addComponent(jRadioButton212))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton101)
                    .addComponent(jRadioButton108)
                    .addComponent(jRadioButton113))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton102)
                    .addComponent(jRadioButton109)
                    .addComponent(jRadioButton114))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton103)
                    .addComponent(jRadioButton110)
                    .addComponent(jRadioButton115))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton104)
                    .addComponent(jRadioButton111))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton105)
                    .addComponent(jRadioButton112))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton106)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton107)
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton201)
                    .addComponent(jRadioButton208)
                    .addComponent(jRadioButton213))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton202)
                    .addComponent(jRadioButton209)
                    .addComponent(jRadioButton214))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton203)
                    .addComponent(jRadioButton210)
                    .addComponent(jRadioButton215))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton204)
                    .addComponent(jRadioButton211))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton205)
                    .addComponent(jRadioButton212))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton206)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton207)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Habitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Habitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Habitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Habitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Habitaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupPiso1;
    private javax.swing.ButtonGroup buttonGroupPiso2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton101;
    private javax.swing.JRadioButton jRadioButton102;
    private javax.swing.JRadioButton jRadioButton103;
    private javax.swing.JRadioButton jRadioButton104;
    private javax.swing.JRadioButton jRadioButton105;
    private javax.swing.JRadioButton jRadioButton106;
    private javax.swing.JRadioButton jRadioButton107;
    private javax.swing.JRadioButton jRadioButton108;
    private javax.swing.JRadioButton jRadioButton109;
    private javax.swing.JRadioButton jRadioButton110;
    private javax.swing.JRadioButton jRadioButton111;
    private javax.swing.JRadioButton jRadioButton112;
    private javax.swing.JRadioButton jRadioButton113;
    private javax.swing.JRadioButton jRadioButton114;
    private javax.swing.JRadioButton jRadioButton115;
    private javax.swing.JRadioButton jRadioButton201;
    private javax.swing.JRadioButton jRadioButton202;
    private javax.swing.JRadioButton jRadioButton203;
    private javax.swing.JRadioButton jRadioButton204;
    private javax.swing.JRadioButton jRadioButton205;
    private javax.swing.JRadioButton jRadioButton206;
    private javax.swing.JRadioButton jRadioButton207;
    private javax.swing.JRadioButton jRadioButton208;
    private javax.swing.JRadioButton jRadioButton209;
    private javax.swing.JRadioButton jRadioButton210;
    private javax.swing.JRadioButton jRadioButton211;
    private javax.swing.JRadioButton jRadioButton212;
    private javax.swing.JRadioButton jRadioButton213;
    private javax.swing.JRadioButton jRadioButton214;
    private javax.swing.JRadioButton jRadioButton215;
    // End of variables declaration//GEN-END:variables
}
