/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misclases;

import controlMySql.MySqlConn;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TheRickbro
 */
public class HabitacionHuesped extends javax.swing.JFrame {

    /**
     * Creates new form HabitacionHuesped
     */
    
    private MySqlConn conn;
    
    public HabitacionHuesped() {
        this.conn = new MySqlConn();
        initComponents();
        this.setLocationRelativeTo(null);
        listaHuespedes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaHuespedes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(21, 19, 19));

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(157, 139, 5));
        jLabel1.setText("Lista de huespedes");

        jTableListaHuespedes.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(157, 139, 5)));
        jTableListaHuespedes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableListaHuespedes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    private void listaHuespedes() {
        
        String query = "select * from huespedes ORDER BY nombre ASC";
        this.conn.Consult(query);
        int n = 0;
        try {
            this.conn.rs.last(); //se posiciona en el ultimo registro de la tabla
            n = this.conn.rs.getRow(); //regresa el numero actual del registro
            this.conn.rs.first();
        }
        catch (Exception e) {
            System.out.println("Error#1 ...");
        }
        if (n !=0 ) {
            System.out.println("n "+n);
            Object datos[][] = new Object[n][9];
            for(int i=0; i<n; i++) { //n total de registros
                try {
                    datos[i][0] = this.conn.rs.getString(1);
                    datos[i][1] = this.conn.rs.getString(2);
                    datos[i][2] = this.conn.rs.getString(3);
                    datos[i][3] = this.conn.rs.getString(4);
                    datos[i][4] = this.conn.rs.getInt(5);
                    datos[i][5] = this.conn.rs.getInt(6);
                    datos[i][6] = this.conn.rs.getString(7);
                    datos[i][7] = this.conn.rs.getInt(8);
                    datos[i][8] = this.conn.rs.getInt(9);
                    //datos[i][9] = this.conn.rs.getInt(10);
                    //String medico = this.conn.rs.getString(4); //no se usa
                    
                    this.conn.rs.next(); // avanzamos un registro
                }
                catch (Exception e) {
                    System.out.println("Error#2 ..."+e.getMessage());
                }
                //String aux = datos[i][3];
                //this.jLabelMostrarDiaSalida.setText(aux);
            }//fin for
            String columnas[] = {"Huesped", "Ciudad", "Fecha ingreso", "Fecha salida", "Habitación", "Piso", "Tipo habitación", "Ocupantes", "Total al ingresar"};
            jTableListaHuespedes.setModel(new DefaultTableModel(datos, columnas));
            
            //String totalsincargos = String.valueOf(datos[0][8]);
            //int totalSC = Integer.parseInt (totalsincargos);
            //int totalFINAL = cuentaTotal + totalSC;
            //String totalMostrar = String.valueOf(totalFINAL); 
            //this.jLabelMostrarTotalPago.setText(totalMostrar);
                    
        } // fin if
        else {
            JOptionPane.showMessageDialog(this, "No hay datos ...");
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HabitacionHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HabitacionHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HabitacionHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HabitacionHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HabitacionHuesped().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaHuespedes;
    // End of variables declaration//GEN-END:variables
}
