/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misclases;

import controlMySql.MySqlConn;
import misclases.Constructores;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author David Emilio
 */
public class Hotel extends javax.swing.JFrame {

    /**
     * Creates new form Hotel
     */
    private MySqlConn conn;
    ArrayList <Constructores> lista = new ArrayList();
    
    public Hotel() {
        
        //simmmm

        this.conn = new MySqlConn();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoHabitacion = new javax.swing.ButtonGroup();
        jPanelRegistro = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombreHuesped = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCiudadOrigen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButtonRecibo = new javax.swing.JButton();
        jLabelFechaSalida = new javax.swing.JLabel();
        jDateChooserIngresar = new com.toedter.calendar.JDateChooser();
        jTextFieldDiasHospedaje = new javax.swing.JTextField();
        jLabelSalida = new javax.swing.JLabel();
        jRadioButtonSencilla = new javax.swing.JRadioButton();
        jRadioButtonDoble = new javax.swing.JRadioButton();
        jRadioButtonTriple = new javax.swing.JRadioButton();
        jComboBoxSencilla = new javax.swing.JComboBox<>();
        jComboBoxDoble = new javax.swing.JComboBox<>();
        jComboBoxTriple = new javax.swing.JComboBox<>();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonElegirHabitacion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelMostrarCargosExtras = new javax.swing.JLabel();
        jLabelMostrarTotalPago = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButtonGaleria = new javax.swing.JButton();
        jButtonHabitacionesDisponibles = new javax.swing.JButton();
        jButtonEstatusHabitacion = new javax.swing.JButton();
        jButtonIngresos = new javax.swing.JButton();
        jButtonListaHuespedes = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonPorcentajeOcupacion = new javax.swing.JButton();
        jButtonPorcentajeOcupacionActual = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atlantis Resort");

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(157, 139, 5)));
        jTabbedPane1.setForeground(new java.awt.Color(157, 139, 5));
        jTabbedPane1.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(21, 19, 19));

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(157, 139, 5));
        jLabel1.setText("Nombre de huesped:");

        jTextFieldNombreHuesped.setBackground(new java.awt.Color(21, 19, 19));
        jTextFieldNombreHuesped.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jTextFieldNombreHuesped.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNombreHuesped.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(157, 139, 5)));

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(157, 139, 5));
        jLabel2.setText("Tipo de habitación:");

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(157, 139, 5));
        jLabel3.setText("Ciudad de origen:");

        jTextFieldCiudadOrigen.setBackground(new java.awt.Color(21, 19, 19));
        jTextFieldCiudadOrigen.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jTextFieldCiudadOrigen.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldCiudadOrigen.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(157, 139, 5)));

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(157, 139, 5));
        jLabel4.setText("Total de personas:");

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(157, 139, 5));
        jLabel5.setText("Total de días de hospedaje:");

        jLabel6.setBackground(new java.awt.Color(161, 146, 5));
        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(157, 139, 5));
        jLabel6.setText("Check-in");

        jLabel12.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(157, 139, 5));
        jLabel12.setText("Fecha de ingreso:");

        jLabel13.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(157, 139, 5));
        jLabel13.setText("Fecha de salida:");

        jButtonRecibo.setBackground(new java.awt.Color(21, 19, 19));
        jButtonRecibo.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jButtonRecibo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRecibo.setText("Generar recibo");
        jButtonRecibo.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(157, 139, 5)));
        jButtonRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReciboActionPerformed(evt);
            }
        });

        jTextFieldDiasHospedaje.setBackground(new java.awt.Color(21, 19, 19));
        jTextFieldDiasHospedaje.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jTextFieldDiasHospedaje.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldDiasHospedaje.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(157, 139, 5)));

        jLabelSalida.setBackground(new java.awt.Color(21, 19, 19));
        jLabelSalida.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabelSalida.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalida.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(157, 139, 5)));

        jRadioButtonSencilla.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTipoHabitacion.add(jRadioButtonSencilla);
        jRadioButtonSencilla.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jRadioButtonSencilla.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSencilla.setText("Sencilla 400€ ");
        jRadioButtonSencilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSencillaActionPerformed(evt);
            }
        });

        jRadioButtonDoble.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTipoHabitacion.add(jRadioButtonDoble);
        jRadioButtonDoble.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jRadioButtonDoble.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonDoble.setText("Doble 500€");
        jRadioButtonDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDobleActionPerformed(evt);
            }
        });

        jRadioButtonTriple.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTipoHabitacion.add(jRadioButtonTriple);
        jRadioButtonTriple.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jRadioButtonTriple.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonTriple.setText("Triple 700€");
        jRadioButtonTriple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTripleActionPerformed(evt);
            }
        });

        jComboBoxSencilla.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jComboBoxSencilla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jComboBoxSencilla.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(157, 139, 5)));
        jComboBoxSencilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSencillaActionPerformed(evt);
            }
        });

        jComboBoxDoble.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jComboBoxDoble.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jComboBoxDoble.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(157, 139, 5)));
        jComboBoxDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDobleActionPerformed(evt);
            }
        });

        jComboBoxTriple.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jComboBoxTriple.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jComboBoxTriple.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(157, 139, 5)));
        jComboBoxTriple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTripleActionPerformed(evt);
            }
        });

        jButtonRegistrar.setBackground(new java.awt.Color(21, 19, 19));
        jButtonRegistrar.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jButtonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrar.setText("Registrar huesped");
        jButtonRegistrar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(157, 139, 5)));
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jButtonElegirHabitacion.setBackground(new java.awt.Color(21, 19, 19));
        jButtonElegirHabitacion.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jButtonElegirHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonElegirHabitacion.setText("Elegir");
        jButtonElegirHabitacion.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(163, 144, 0)));
        jButtonElegirHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonElegirHabitacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNombreHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonSencilla, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(jRadioButtonDoble)
                                        .addGap(66, 66, 66)
                                        .addComponent(jRadioButtonTriple)
                                        .addGap(92, 92, 92)
                                        .addComponent(jButtonElegirHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jDateChooserIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jComboBoxSencilla, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(jComboBoxDoble, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addComponent(jComboBoxTriple, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButtonRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelSalida))
                                        .addGap(245, 245, 245)
                                        .addComponent(jLabelFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldDiasHospedaje, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(494, 494, 494)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabelFechaSalida, jLabelSalida, jTextFieldCiudadOrigen, jTextFieldNombreHuesped});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBoxDoble, jComboBoxSencilla, jComboBoxTriple});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel6)
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldNombreHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jRadioButtonSencilla)
                            .addComponent(jRadioButtonDoble)
                            .addComponent(jRadioButtonTriple)
                            .addComponent(jButtonElegirHabitacion))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxSencilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxDoble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTriple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(jLabel12))
                    .addComponent(jDateChooserIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldDiasHospedaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabelSalida))
                    .addComponent(jLabelFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRegistrar))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelFechaSalida, jLabelSalida, jTextFieldCiudadOrigen, jTextFieldDiasHospedaje, jTextFieldNombreHuesped});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBoxDoble, jComboBoxSencilla, jComboBoxTriple});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jRadioButtonDoble, jRadioButtonSencilla, jRadioButtonTriple});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonRecibo, jButtonRegistrar});

        jTabbedPane1.addTab("Registro", jPanel2);

        jPanel3.setBackground(new java.awt.Color(21, 19, 19));

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(157, 139, 5));
        jLabel7.setText("Check-out");

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(157, 139, 5));
        jLabel8.setText("Número de habitación:");

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(157, 139, 5));
        jLabel9.setText("Total a pagar:");

        jLabel10.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(157, 139, 5));
        jLabel10.setText("Días de estadia:");

        jLabel11.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(157, 139, 5));
        jLabel11.setText("Cargos extras:");

        jLabelMostrarCargosExtras.setBackground(new java.awt.Color(21, 19, 19));
        jLabelMostrarCargosExtras.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabelMostrarCargosExtras.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(157, 139, 5)));

        jLabelMostrarTotalPago.setBackground(new java.awt.Color(21, 19, 19));
        jLabelMostrarTotalPago.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabelMostrarTotalPago.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMostrarTotalPago.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(157, 139, 5)));

        jLabel14.setBackground(new java.awt.Color(21, 19, 19));
        jLabel14.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(157, 139, 5)));

        jLabel15.setBackground(new java.awt.Color(21, 19, 19));
        jLabel15.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(157, 139, 5)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMostrarCargosExtras, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMostrarTotalPago, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addContainerGap(343, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(431, 431, 431))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel14, jLabel15, jLabelMostrarCargosExtras, jLabelMostrarTotalPago});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel7)
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel14))
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15))
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabelMostrarCargosExtras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabelMostrarTotalPago))
                .addGap(142, 142, 142))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel14, jLabel15, jLabelMostrarCargosExtras, jLabelMostrarTotalPago});

        jTabbedPane1.addTab("Salida", jPanel3);

        jPanel4.setBackground(new java.awt.Color(21, 19, 19));

        jButtonGaleria.setBackground(new java.awt.Color(21, 19, 19));
        jButtonGaleria.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jButtonGaleria.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGaleria.setText("Galeria");
        jButtonGaleria.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(157, 139, 5)));

        jButtonHabitacionesDisponibles.setBackground(new java.awt.Color(21, 19, 19));
        jButtonHabitacionesDisponibles.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jButtonHabitacionesDisponibles.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHabitacionesDisponibles.setText("Habitaciones disponibles");
        jButtonHabitacionesDisponibles.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(157, 139, 5)));

        jButtonEstatusHabitacion.setBackground(new java.awt.Color(21, 19, 19));
        jButtonEstatusHabitacion.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jButtonEstatusHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEstatusHabitacion.setText("Estatus de habitación");
        jButtonEstatusHabitacion.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(157, 139, 5)));

        jButtonIngresos.setBackground(new java.awt.Color(21, 19, 19));
        jButtonIngresos.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jButtonIngresos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIngresos.setText("Ingresos");
        jButtonIngresos.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(157, 139, 5)));

        jButtonListaHuespedes.setBackground(new java.awt.Color(21, 19, 19));
        jButtonListaHuespedes.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jButtonListaHuespedes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListaHuespedes.setText("Consultar lista de huespedes");
        jButtonListaHuespedes.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(157, 139, 5)));

        jButton2.setBackground(new java.awt.Color(21, 19, 19));
        jButton2.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Total de habitaciones");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(157, 139, 5)));

        jButtonPorcentajeOcupacion.setBackground(new java.awt.Color(21, 19, 19));
        jButtonPorcentajeOcupacion.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jButtonPorcentajeOcupacion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPorcentajeOcupacion.setText("Porcentaje de ocupación");
        jButtonPorcentajeOcupacion.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(157, 139, 5)));

        jButtonPorcentajeOcupacionActual.setBackground(new java.awt.Color(21, 19, 19));
        jButtonPorcentajeOcupacionActual.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jButtonPorcentajeOcupacionActual.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPorcentajeOcupacionActual.setText("Porcentaje de ocupación actual");
        jButtonPorcentajeOcupacionActual.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(157, 139, 5)));

        jButton3.setBackground(new java.awt.Color(21, 19, 19));
        jButton3.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Buscar huesped");
        jButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(157, 139, 5)));

        jButton4.setBackground(new java.awt.Color(21, 19, 19));
        jButton4.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Costos de habitación");
        jButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(157, 139, 5)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(544, 544, 544)
                        .addComponent(jButtonGaleria)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHabitacionesDisponibles)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton2)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButtonPorcentajeOcupacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonPorcentajeOcupacionActual))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonEstatusHabitacion)
                                .addGap(10, 10, 10))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButtonListaHuespedes)
                                .addGap(73, 73, 73)
                                .addComponent(jButtonIngresos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(63, 63, 63))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton2, jButton3, jButton4, jButtonEstatusHabitacion, jButtonGaleria, jButtonHabitacionesDisponibles, jButtonIngresos, jButtonListaHuespedes, jButtonPorcentajeOcupacion, jButtonPorcentajeOcupacionActual});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonListaHuespedes)
                    .addComponent(jButtonIngresos))
                .addGap(134, 134, 134)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHabitacionesDisponibles)
                    .addComponent(jButton4)
                    .addComponent(jButtonEstatusHabitacion))
                .addGap(133, 133, 133)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButtonPorcentajeOcupacion)
                    .addComponent(jButtonPorcentajeOcupacionActual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(jButtonGaleria)
                .addGap(40, 40, 40))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton2, jButton3, jButton4, jButtonEstatusHabitacion, jButtonGaleria, jButtonHabitacionesDisponibles, jButtonIngresos, jButtonListaHuespedes, jButtonPorcentajeOcupacion, jButtonPorcentajeOcupacionActual});

        jTabbedPane1.addTab("Consultas", jPanel4);

        jPanel5.setBackground(new java.awt.Color(21, 19, 19));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1186, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Salir", jPanel5);

        javax.swing.GroupLayout jPanelRegistroLayout = new javax.swing.GroupLayout(jPanelRegistro);
        jPanelRegistro.setLayout(jPanelRegistroLayout);
        jPanelRegistroLayout.setHorizontalGroup(
            jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelRegistroLayout.setVerticalGroup(
            jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:

        String huesped, ciudad, habitacion, tipoHabitacion, diasHospedaje, aux;
        int piso, totalconCargos, totalsinCargos, totalPersonas, parcial=0;

        String diaLlegada = "" + jDateChooserIngresar.getDate();
        SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd");
        diaLlegada = Date_Format.format(jDateChooserIngresar.getDate());

        huesped = this.jTextFieldNombreHuesped.getText().trim();
        ciudad = this.jTextFieldCiudadOrigen.getText().trim();
        System.out.println(huesped + "\n");
        System.out.println(ciudad + "\n");
        if (this.jRadioButtonSencilla.isSelected()) {
            tipoHabitacion = "Sencilla";
            parcial+=400;
            aux = (String) this.jComboBoxSencilla.getSelectedItem();
            totalPersonas = Integer.parseInt (aux);
            if(totalPersonas>1)
                parcial+=70*(totalPersonas-1);
        } else if (this.jRadioButtonDoble.isSelected()) {
            tipoHabitacion = "Doble";
            parcial+=500;
            aux = (String) this.jComboBoxDoble.getSelectedItem();
            totalPersonas = Integer.parseInt (aux);
            if(totalPersonas>2)
                parcial+=70*(totalPersonas-2);           
        } else {
            tipoHabitacion = "Triple";
            parcial+=700;
            aux = (String) this.jComboBoxTriple.getSelectedItem();
            totalPersonas = Integer.parseInt (aux);
            if(totalPersonas>3)
                parcial+=70*(totalPersonas-3); 
        }
        System.out.println(tipoHabitacion + "\n");
        System.out.println(totalPersonas + "\n");

        // Obtener fecha
        diasHospedaje = this.jTextFieldDiasHospedaje.getText().trim();

        int dia2 = Integer.valueOf(diasHospedaje);
        int d = this.jDateChooserIngresar.getCalendar().get(Calendar.DAY_OF_MONTH);
        int m = this.jDateChooserIngresar.getCalendar().get(Calendar.MONTH);
        int a = this.jDateChooserIngresar.getCalendar().get(Calendar.YEAR);

        String dia = String.valueOf(d);
        String mes = String.valueOf(m);
        String ani = String.valueOf(a);
        String fecha = ani + "-" + mes + "-" + dia;
        String[] f = fecha.split("-");

        Calendar calendario = Calendar.getInstance();
        calendario.set(Integer.parseInt(f[0]), Integer.parseInt(f[1]), Integer.parseInt(f[2]));
        calendario.add(Calendar.DAY_OF_MONTH, dia2);
        
        SimpleDateFormat diaMostrar = new SimpleDateFormat("EEEE, d 'de' MMMM 'de' yyyy");
        this.jLabelSalida.setText(diaMostrar.format(calendario.getTime()));
        
        SimpleDateFormat diaSalida = new SimpleDateFormat("yyyy-MM-dd");
        diaSalida.format(calendario.getTime());
        String diaSalida2 = diaSalida.format(calendario.getTime());
        
        habitacion = "500";
        piso = 1;
        totalconCargos = 2;
        totalsinCargos = parcial;
     
        String parte1 = "Insert into huespedes (nombre, ciudad, fechaingreso, fechasalida, numhabitacion, piso, tipohabitacion, ocupantes, totalsincargos, totalconcargos) VALUES (";
        String parte2 = "'" + huesped + "','" + ciudad + "','" + diaLlegada + "','" + diaSalida2+ "','" + habitacion + "', '" + piso + "', '" + tipoHabitacion + "', '" + totalPersonas + "','" + totalsinCargos + "', '" + totalconCargos + "')";
        String querry = parte1 + parte2;
        int j = this.conn.Update(querry);
        System.out.println("Numero de registros afectados por la accion: " + j);
        
        this.jTextFieldNombreHuesped.setText("");
        this.jTextFieldCiudadOrigen.setText("");
        this.jTextFieldDiasHospedaje.setText("");
        
        Constructores obj;
        obj = new Constructores(huesped,ciudad, habitacion, tipoHabitacion, diasHospedaje, diaLlegada, diaSalida2, piso, totalconCargos, totalsinCargos, totalPersonas);
        lista.add(obj);
        //RecibirDatos(huesped);
        /*for(int i=0; i<lista.size(); i++)
            System.out.println(" Lista "+lista.get(i).getHuesped());*/

    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jRadioButtonTripleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTripleActionPerformed
        // TODO add your handling code here:
        
        String band;
        this.jComboBoxSencilla.setEnabled(false);
        this.jComboBoxDoble.setEnabled(false);
        this.jComboBoxTriple.setEnabled(true);
        band="3";
        new Habitaciones(band).setVisible(true);
    }//GEN-LAST:event_jRadioButtonTripleActionPerformed

    private void jRadioButtonDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDobleActionPerformed
        // TODO add your handling code here:
        
        String band;
        this.jComboBoxSencilla.setEnabled(false);
        this.jComboBoxDoble.setEnabled(true);
        this.jComboBoxTriple.setEnabled(false);
        band="2";
        new Habitaciones(band).setVisible(true);
    }//GEN-LAST:event_jRadioButtonDobleActionPerformed

    private void jRadioButtonSencillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSencillaActionPerformed
        // TODO add your handling code here:
        
        
        String band;
        this.jComboBoxSencilla.setEnabled(true);
        this.jComboBoxDoble.setEnabled(false);
        this.jComboBoxTriple.setEnabled(false);
        band="1";
        new Habitaciones(band).setVisible(true);
    }//GEN-LAST:event_jRadioButtonSencillaActionPerformed

    private void jButtonElegirHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonElegirHabitacionActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButtonElegirHabitacionActionPerformed

    private void jButtonReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReciboActionPerformed
        // TODO add your handling code here:
        //new GenerarRecibo(lista).setVisible(true);
        new GenerarRecibo(lista).setVisible(true);
        
    }//GEN-LAST:event_jButtonReciboActionPerformed

    private void jComboBoxSencillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSencillaActionPerformed
        // TODO add your handling code here:
                  
        if(this.jComboBoxSencilla.getSelectedItem()=="2"||this.jComboBoxSencilla.getSelectedItem()=="3")
            JOptionPane.showMessageDialog(null, "Capacidad máxima de 1 huesped\nCada persona extra pagará 70€");
    }//GEN-LAST:event_jComboBoxSencillaActionPerformed

    private void jComboBoxDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDobleActionPerformed
        // TODO add your handling code here:
        
        if(this.jComboBoxDoble.getSelectedItem()=="3"||this.jComboBoxDoble.getSelectedItem()=="4")
            JOptionPane.showMessageDialog(null, "Capacidad máxima de 2 huespedes\nCada persona extra pagará 70€");
    }//GEN-LAST:event_jComboBoxDobleActionPerformed

    private void jComboBoxTripleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTripleActionPerformed
        // TODO add your handling code here:
        
        if(this.jComboBoxTriple.getSelectedItem()=="4"||this.jComboBoxTriple.getSelectedItem()=="5")
            JOptionPane.showMessageDialog(null, "Capacidad máxima de 3 huespedes\nCada persona extra pagará 70€");
    }//GEN-LAST:event_jComboBoxTripleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hotel().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTipoHabitacion;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonElegirHabitacion;
    private javax.swing.JButton jButtonEstatusHabitacion;
    private javax.swing.JButton jButtonGaleria;
    private javax.swing.JButton jButtonHabitacionesDisponibles;
    private javax.swing.JButton jButtonIngresos;
    private javax.swing.JButton jButtonListaHuespedes;
    private javax.swing.JButton jButtonPorcentajeOcupacion;
    private javax.swing.JButton jButtonPorcentajeOcupacionActual;
    private javax.swing.JButton jButtonRecibo;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JComboBox<String> jComboBoxDoble;
    private javax.swing.JComboBox<String> jComboBoxSencilla;
    private javax.swing.JComboBox<String> jComboBoxTriple;
    private com.toedter.calendar.JDateChooser jDateChooserIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFechaSalida;
    private javax.swing.JLabel jLabelMostrarCargosExtras;
    private javax.swing.JLabel jLabelMostrarTotalPago;
    private javax.swing.JLabel jLabelSalida;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelRegistro;
    private javax.swing.JRadioButton jRadioButtonDoble;
    private javax.swing.JRadioButton jRadioButtonSencilla;
    private javax.swing.JRadioButton jRadioButtonTriple;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldCiudadOrigen;
    private javax.swing.JTextField jTextFieldDiasHospedaje;
    private javax.swing.JTextField jTextFieldNombreHuesped;
    // End of variables declaration//GEN-END:variables
}
